server.port: 8086

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/departement?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username : root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql : true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level:
      org:
        hibernate:
          type: trace
          stat: debug